/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MigrateSalesrepRequest {
    /**
     * salesRepId for salesrep whose realm we'd like to migrate
     */
    salesRepId: string;
    /**
     * optional schema version to migrate to (else most-recent)
     */
    schemaVersion?: number;
}
