/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Header, Provider} from '../model';

export interface UpsertProviderResponse {
    header: Header;
    provider?: Provider;
    /**
     * Used when the process to add is async, this can be used to get the status of the request
     */
    responseId?: string;
}
