/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {GoogleGeocode} from './GoogleGeocode';
import {Time} from './Time';

export interface Addresses {
    address1: string;
    address2: string;
    addressPurpose?: string;
    addressType?: string;
    businessName?: string;
    city: string;
    countryCode?: string;
    countryName?: string;
    faxNumber?: string;
    googleGeocode: GoogleGeocode;
    postalCode: string;
    state: string;
    telephoneNumber?: string;
    times?: Time[];
    website?: string;
}