/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {AreaGraphSeries} from './AreaGraphSeries';

export interface AreaGraph {
    primaryData: AreaGraphSeries;
    secondaryData?: AreaGraphSeries;
    summaryMetric: string;
    title: string;
}