/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BasicInfo {
    credential?: string;
    deactivationDate?: string;
    enumerationDate?: string;
    firstName: string;
    gender?: string;
    lastName: string;
    lastUpdated?: string;
    middleName?: string;
    name: string;
    namePrefix?: string;
    reactivationDate?: string;
    soleProprietor?: string;
    status?: string;
}