/**
 * SalesRep API
 * Sales Rep Backend APIs
 *
 * OpenAPI spec version: 0.0.55
 * Contact: theodore.dasher@roivant.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Addresses} from './Addresses';
import {CallLogResponse} from './CallLogResponse';
import {Header} from './Header';

export interface CallLog {
    appointmentType: string;
    callDate: Date;
    callLocation?: Addresses;
    callLogFormId: string;
    callLogId: string;
    hasTime: boolean;
    header: Header;
    logDate: Date;
    logDatePriorityIndex?: number;
    logLocationLat?: number;
    logLocationLon?: number;
    npiNumber: number;
    productCodes: string[];
    providerId: string;
    responses?: CallLogResponse[];
    salesRepId: string;
    scheduleDatePriorityIndex: number;
}
